[book]
authors = ["Gastrodia"]
language = "zh"
multilingual = false
src = "src"
title = "Rust学习笔记"

[output.html.playground]
editable = true
copy-js = true

[output.html.fold]
enable = true
level = 0
