[book]
authors = ["Gastrodia"]
language = "zh"
multilingual = false
src = "src"
title = "Rust学习笔记"


[output.html]
additional-js = ["assets/bigPicture.js", "assets/custom.js"]
git-repository-url = "https://github.com/gastrodia/note-rust"

[output.html.playground]
editable = true
copy-js = true

[output.html.fold]
enable = true
level = 1

[output.html.print]
enable = false
